name: vectra-ai

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: vectra-qdrant
    restart: unless-stopped

    volumes:
      - qdrant_storage:/qdrant/storage

    networks:
      - vectra-network

  n8n:
    image: n8nio/n8n:latest
    container_name: vectra-n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${TZ}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - N8N_RESTRICT_FILE_ACCESS_TO=/files

    volumes:
      - n8n_data:/home/node/.n8n
      - ../../docs/pdf/knowledge:/files:ro

    depends_on:
      - qdrant

    networks:
      - vectra-network

volumes:
  n8n_data:
  qdrant_storage:

networks:
  vectra-network:
    driver: bridge